account/urls.py
from django.conf.urls import patterns, url
from account import views

urlpatterns = patterns(
    '',
    url(r'^$', views.login, name='login'),
    url(r'^index/$', views.index, name='index'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^my_files/$', views.my_files, name='my_files'),
    url(r'^change_name/$', views.change_name, name='change_name'),
    url(r'^remove_resource/$', views.remove_resource, name='remove_resource'),
    url(r'^player/$', views.player, name='player'),
    url(r'^create_cast/$', views.create_cast, name='create_cast'),
    url(r'^groups/$', views.groups, name='groups'),
    url(r'^complete_users_and_groups/(?P<completion_string>\w+)/$', views.complete_users_and_groups, name='complete_usernames'),
    url(r'^profile/share/$', views.share, name='share'),
    url(r'^share_add_users/$', views.share_add_users, name='share_add_users'),
    url(r'^groups/create_group/$', views.create_group, name='create_group'),
    url(r'^groups/get_group/$', views.get_group, name='get_group'),
    url(r'^launch_applet/$', views.launch_applet, name='launch_applet'),
)

screencast/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^accounts/login/$', 'django_cas.views.login', name='login'),
    url(r'^accounts/logout/$', 'django_cas.views.logout', name='logout'),
)

templates/base.html
<html>
    <head>
        <title>{% block title %}Screencast{% endblock %}</title>
        <link rel="stylesheet" href="{{ STATIC_URL }}styles/global.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/bootstrap.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
        <script type="text/javascript" src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.form.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/underscore.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/common.js"></script>

        {% block head %}
        {% endblock %}
    </head>
    <body>
        <div id="navbar">
        {% load url from future %}
        <ul>
            <li class="{% block tab1 %}inactive{% endblock %}"><a href="{% url 'account:index' %}">Index</a></li>
            <li class="{% block tab2 %}inactive{% endblock %}"><a href="{% url 'account:my_files' %}">My files</a></li>
            <li class="{% block tab3 %}inactive{% endblock %}"><a href="{% url 'account:player' %}">Player</a></li>
            <li class="{% block tab4 %}inactive{% endblock %}"><a href="{% url 'account:groups' %}">Groups</a></li>
            <li class="{% block tab5 %}inactive{% endblock %}"><a href="{% url 'account:launch_applet' %}">Applet</a></li>
            {% if request.user.is_authenticated %}
                <li class="login"><a href="{% url 'logout' %}">Log out</a></li>
            {% else %}
                <li class="login"><a href="{% url 'login' %}">Log in</a></li>
            {% endif %}
        </ul>
        </div>
        <div class="main">
        {% block main %}Add content..{% endblock %}
        </div>
    </body>
</html>